### PR TITLE
MWPW-136489: Fix Linting Issues

### PR DESCRIPTION
**Pull request by JasonHowellSlavin**
- Modifies eslint for our needs (node.js instead of web)
- Attempted to import utils directly and installing, but importing the latest caused errors in tests for the select utils
- added "disable" rules where refactoring may have been too time consuming
- added additional files to ignore list that are outdated

### CODE REVIEW

**Comment by Brandon32** [comment]
@JasonHowellSlavin We should install unist-util-select@4.0.3 so we don't accidentally break select in the future and we can remove the eslint exception.

**Comment by JasonHowellSlavin** [comment]
> @JasonHowellSlavin We should install unist-util-select@4.0.3 so we don't accidentally break select in the future and we can remove the eslint exception.

> * Attempted to import utils directly and installing, but importing the latest caused errors in tests for the select utils

I did attempt an install. Probably an issue we raise to this repo to install it as a dependency and grab the latest, and fix the two tests it was breaking. Thought that was a touch out of scope of this current ticket. What do you think?

**Review by Brandon32 — APPROVED** [review]

**Comment by Brandon32** [comment]
> > @JasonHowellSlavin We should install unist-util-select@4.0.3 so we don't accidentally break select in the future and we can remove the eslint exception.
> 
> > * Attempted to import utils directly and installing, but importing the latest caused errors in tests for the select utils
> 
> I did attempt an install. Probably an issue we raise to this repo to install it as a dependency and grab the latest, and fix the two tests it was breaking. Thought that was a touch out of scope of this current ticket. What do you think?

I assumed it installed 5.1.0 and that's why it was breaking, I installed 4.0.3 and had no issues with the test. Thought it would be a quick fix but I'm good with creating an issue to fix the tests with the latest version.

**Comment by JasonHowellSlavin** [comment]
Added issue: https://github.com/adobecom/bulk-updater/issues/25

**Pull request merged**
